// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqtv0-TGVylvdqArvnSD8693soI9mdSwo',
    appId: '1:362905085279:web:4291fe014a9c318d0842ea',
    messagingSenderId: '362905085279',
    projectId: 'mangamanialeakcode',
    authDomain: 'mangamanialeakcode.firebaseapp.com',
    storageBucket: 'mangamanialeakcode.appspot.com',
    measurementId: 'G-F7K2TGXFBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB86ReJwb8ib6bWJ_Wc040GG9C3YupJaMw',
    appId: '1:362905085279:android:e7268f4f6bd4afd40842ea',
    messagingSenderId: '362905085279',
    projectId: 'mangamanialeakcode',
    storageBucket: 'mangamanialeakcode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbfbkE9xpjAil255COQqeVztWdSp8hmSA',
    appId: '1:362905085279:ios:33a91bcab77ae28a0842ea',
    messagingSenderId: '362905085279',
    projectId: 'mangamanialeakcode',
    storageBucket: 'mangamanialeakcode.appspot.com',
    iosBundleId: 'com.example.mangaMania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbfbkE9xpjAil255COQqeVztWdSp8hmSA',
    appId: '1:362905085279:ios:33a91bcab77ae28a0842ea',
    messagingSenderId: '362905085279',
    projectId: 'mangamanialeakcode',
    storageBucket: 'mangamanialeakcode.appspot.com',
    iosBundleId: 'com.example.mangaMania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqtv0-TGVylvdqArvnSD8693soI9mdSwo',
    appId: '1:362905085279:web:e077089d74bd5bf90842ea',
    messagingSenderId: '362905085279',
    projectId: 'mangamanialeakcode',
    authDomain: 'mangamanialeakcode.firebaseapp.com',
    storageBucket: 'mangamanialeakcode.appspot.com',
    measurementId: 'G-LWH2BMZ732',
  );
}
